package keyenc

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// fixturePath is the cross-language golden fixture. Both implementations read
// it: this test pins that Go produces these keys, and web/src/keyenc.test.ts
// pins that TypeScript produces the same ones. It is the only mechanism that
// keeps the two halves byte-identical, which the forge-id call sites need
// because a key built in one language is looked up against keys built in the
// other.
const fixturePath = "conformance/keys.json"

// regenCmd and consumerTest are named in every failure message: a mismatch is
// either a deliberate grammar change (regenerate, then re-run the TypeScript
// half in the same commit) or a real divergence.
const (
	regenCmd     = "UPDATE_GOLDEN=1 go test ./... -run TestConformanceFixture"
	consumerTest = "cd web && npm test"
)

type conformanceCase struct {
	Name  string   `json:"name"`
	Parts []string `json:"parts"`
	Key   string   `json:"key"`
}

type conformanceFile struct {
	Note  string            `json:"note"`
	Cases []conformanceCase `json:"cases"`
}

// conformanceInputs are the component sets the fixture pins. Every case is
// valid UTF-8 on purpose: a JSON fixture cannot carry an unpaired surrogate,
// and a JavaScript string cannot represent Go's arbitrary bytes, so the
// invalid-UTF-8 half of the input space is covered by FuzzJoinSplitInjective on
// the Go side alone. What the fixture must cover is every case where the two
// implementations could plausibly disagree: the escapes, the degenerate sets,
// the size bound (measured in UTF-8 BYTES, not UTF-16 code units), the hashing,
// and multibyte text near all of them.
func conformanceInputs() []conformanceCase {
	overBound := strings.Repeat("x", MaxComponentBytes+1)
	// A component whose UTF-16 length is under the bound while its UTF-8 byte
	// length is over it. A TypeScript implementation measuring .length instead
	// of encoded bytes returns an escaped join here where Go returns a hash.
	multibyteOverBound := strings.Repeat("é", MaxComponentBytes/2+1)
	return []conformanceCase{
		{Name: "empty set", Parts: []string{}},
		{Name: "single empty component", Parts: []string{""}},
		{Name: "two empty components", Parts: []string{"", ""}},
		{Name: "plain pair", Parts: []string{"a", "b"}},
		{Name: "forge id default host", Parts: []string{"github", "github.com"}},
		{Name: "forge id with port", Parts: []string{"gitea", "git.example.com:3000"}},
		{Name: "persisted stream key", Parts: []string{"streams", "u-42", "1234", "3", "5"}},
		{Name: "virtual pending path", Parts: []string{"pending", "c-1", "call-abc"}},
		{Name: "separator in head", Parts: []string{"a:b", "c"}},
		{Name: "separator in tail", Parts: []string{"a", "b:c"}},
		{Name: "escape in component", Parts: []string{`a\b`, "c"}},
		{Name: "escaped separator literal", Parts: []string{`a\:b`, "c"}},
		{Name: "double escape", Parts: []string{`\\`, `\`}},
		{Name: "only separators", Parts: []string{"::", ":"}},
		{Name: "empty middle", Parts: []string{"a", "", "c"}},
		{Name: "rename idempotency key", Parts: []string{"files.rename", "dir/x->y", "z"}},
		{Name: "hashed prefix spelled raw", Parts: []string{"sha256", strings.Repeat("0", hashedHexLen)}},
		{Name: "multibyte components", Parts: []string{"café", "naïve:ü"}},
		{Name: "emoji with separator", Parts: []string{"🔑:a", "b"}},
		{Name: "combining marks", Parts: []string{"e\u0301", "e\u0301:x"}},
		{Name: "nested inner join", Parts: []string{"outer", Join("in:a", "in:b")}},
		{Name: "at the size bound", Parts: []string{strings.Repeat("x", MaxComponentBytes)}},
		{Name: "over the size bound", Parts: []string{overBound}},
		{Name: "over the bound in two parts", Parts: []string{strings.Repeat("x", 5000), strings.Repeat("y", 4000)}},
		{Name: "multibyte over the byte bound", Parts: []string{multibyteOverBound}},
		{Name: "oversized with separators", Parts: []string{strings.Repeat(":", MaxComponentBytes+1)}},
	}
}

// TestConformanceFixture pins Go's output for every conformance case and, under
// UPDATE_GOLDEN=1, regenerates the fixture the TypeScript half reads. Writing
// and comparing share this one code path so the fixture cannot drift from what
// the encoder actually does.
func TestConformanceFixture(t *testing.T) {
	want := conformanceInputs()
	for i := range want {
		want[i].Key = Join(want[i].Parts...)
	}
	payload := conformanceFile{
		Note: "Generated by TestConformanceFixture (" + regenCmd + "). " +
			"Read by both keyenc implementations; the TypeScript half must produce byte-identical keys. " +
			"Cases are valid UTF-8 only: a JSON fixture cannot carry Go's arbitrary bytes.",
		Cases: want,
	}
	encoded, err := json.MarshalIndent(payload, "", "  ")
	if err != nil {
		t.Fatalf("marshal fixture: %v", err)
	}
	encoded = append(encoded, '\n')

	if os.Getenv("UPDATE_GOLDEN") == "1" {
		if err := os.MkdirAll(filepath.Dir(fixturePath), 0o750); err != nil {
			t.Fatalf("create fixture dir: %v", err)
		}
		if err := os.WriteFile(fixturePath, encoded, 0o600); err != nil {
			t.Fatalf("write fixture: %v", err)
		}
		t.Logf("regenerated %s (%d cases); re-run the TypeScript half: %s", fixturePath, len(want), consumerTest)
		return
	}

	got, err := os.ReadFile(fixturePath)
	if err != nil {
		t.Fatalf("read golden %s (run %s): %v", fixturePath, regenCmd, err)
	}
	if !bytes.Equal(got, encoded) {
		t.Errorf("fixture %s is stale (%d bytes on disk, %d generated).\n"+
			"Regenerate with: %s\nThen re-run the consumer: %s",
			fixturePath, len(got), len(encoded), regenCmd, consumerTest)
	}
}

// TestConformanceCasesCoverBothRegimes guards the fixture's own usefulness: a
// case list that drifted entirely below the size bound would still pass
// TestConformanceFixture while silently stopping to pin the hashing half, where
// the two implementations are most likely to diverge (UTF-8 byte counting and
// the length-prefixed digest).
func TestConformanceCasesCoverBothRegimes(t *testing.T) {
	var raw, hashed int
	for _, c := range conformanceInputs() {
		if IsHashed(Join(c.Parts...)) {
			hashed++
		} else {
			raw++
		}
	}
	if raw == 0 || hashed == 0 {
		t.Errorf("fixture must exercise both regimes: %d raw, %d hashed", raw, hashed)
	}
}
